version: '3.8'

services:

  mock:
    build:
      context: ./app-nt-mock
    ports:
      - "8080:8080"
      - "6565:6565"
    networks:
      - nt-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M

  platform-thread:
    build:
      context: ./app-nt-platform-thread
    ports:
      - "8081:8081"
    depends_on:
      - mock
    networks:
      - nt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  virtual-thread:
    build:
      context: ./app-nt-virtual-thread
    ports:
      - "8082:8082"
    depends_on:
      - mock
    networks:
      - nt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  webflux:
    build:
      context: ./app-nt-webflux
    ports:
      - "8083:8083"
    depends_on:
      - mock
    networks:
      - nt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  golang-service:
    build:
      context: ./app-nt-golang
    ports:
      - "8084:8084"
    depends_on:
      - mock
    networks:
      - nt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nt-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - nt-network
    depends_on:
      - prometheus

networks:
  nt-network:
    driver: bridge