global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'mock'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mock:8080']

  - job_name: 'platform-thread'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['platform-thread:8081']

  - job_name: 'virtual-thread'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'virtual-thread:8082' ]

  - job_name: 'webflux'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'webflux:8083' ]