
server:
  port: 8080

spring:
  application:
    name: app-nt-mock
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true